controller_credentials:

- name: 'Azure'
  credential_type: 'Microsoft Azure Resource Manager'
  description: 'Azure Subscription'
  inputs:
    client: '{{ azure.client }}'
    cloud_environment: '{{ azure.cloud_environment }}'
    password: '{{ azure.password }}'
    secret: '{{ azure.secret }}'
    subscription: '{{ azure.subscription }}'
    tenant: '{{ azure.tenant }}'
    username: '{{ azure.username }}'
  organization: '{{ org_name }}'


- name: 'GitHub Website'
  credential_type: 'GitHub Personal Access Token'
  description: ''
  inputs: '{}'
  organization: '{{ org_name }}'


- name: 'Linux'
  credential_type: 'Machine'
  description: 'Account for doing automation inside Linux machines'
  inputs:
    become_method: 'sudo'
    become_password: '{{ demo_password }}'
    become_username: 'root'
    ssh_key_data: '{{ private_key }}'
    username: 'ansible'
  organization: '{{ org_name }}'


- name: 'Proxy Stats'
  credential_type: 'Vault'
  description: 'Credential to access the haproxy vault with the username/password to access the stats page'
  inputs:
    vault_id: ''
    vault_password: '{{ demo_password }}'
  organization: '{{ org_name }}'


- name: 'Windows'
  credential_type: 'Machine'
  description: 'Account for doing automation inside Windows machines'
  inputs:
    become_method: 'runas'
    become_username: 'Administrator'
    username: 'ansible'
    password: '{{ demo_password }}'
  organization: '{{ org_name }}'

