controller_inventory_sources:
- name: 'Azure'
  description: 'All instances in Azure'
  source: 'azure_rm'
  credential: 'Azure'
  inventory: 'Cloud'
  source_vars:
    hostnames:
    - computer_name
    keyed_groups:
    - prefix: role
      key: tags.role | default('none') 
