controller_roles:
- user: 'cloudguy'
  target_team: 'Cloud Team'
  role: 'member'
- user: 'contentguy'
  target_team: 'Content Team'
  role: 'member'
- user: 'databaseguy'
  target_team: 'Database Team'
  role: 'member'
- user: 'linuxguy'
  target_team: 'Linux Team'
  role: 'member'
- user: 'networkguy'
  target_team: 'Network Team'
  role: 'member'
- user: 'storageguy'
  target_team: 'Storage Team'
  role: 'member'
- user: 'webguy'
  target_team: 'Web Team'
  role: 'member'
- user: 'windowsguy'
  target_team: 'Windows Team'
  role: 'member'

- team: 'Cloud Team'
  role: 'read'
- team: 'Content Team'
  role: 'read'
- team: 'Database Team'
  role: 'read'
- team: 'Linux Team'
  role: 'read'
- team: 'Network Team'
  role: 'read'
- team: 'Storage Team'
  role: 'read'
- team: 'Web Team'
  role: 'read'
- team: 'Windows Team'
  role: 'read'

- team: 'Cloud Team'
  role: 'admin'
  workflow: 'Deploy Web Farm'
- team: 'Cloud Team'
  role: 'approval'
  workflow: 'Deploy Web Farm'
- team: 'Web Team'
  role: 'execute'
  workflow: 'Deploy Web Farm'

- team: 'Linux Team'
  role: 'admin'
  job_template: 'Rolling update Webfarm'

