controller_teams:
- name: 'Cloud Team'
  description: 'Manages all cloud resources'
  organization: '{{ org_name }}'
- name: 'Content Team'
  description: 'Team that manages content'
  organization: '{{ org_name }}'
- name: 'Database Team'
  description: 'The infamous Database Team that rule all data'
  organization: '{{ org_name }}'
- name: 'Linux Team'
  description: 'The FOSS guys'
  organization: '{{ org_name }}'
- name: 'Network Team'
  description: 'The team that connects everybody'
  organization: '{{ org_name }}'
- name: 'Storage Team'
  description: 'The statefull team'
  organization: '{{ org_name }}'
- name: 'Web Team'
  description: 'Managed all Web resources'
  organization: '{{ org_name }}'
- name: 'Windows Team'
  description: 'The team that manages all Windows machines'
  organization: '{{ org_name }}'

