controller_templates:
- name: Deploy common Azure resources
  description: ''
  execution_environment: Azure Execution Environment
  extra_vars:
    ansible_python_interpreter: /usr/bin/python3
  inventory: Cloud
  playbook: azure_create_common.yml
  project: Azure Playbooks
  credentials: Azure
  survey_enabled: true
  related:
    survey_spec:
      name: ''
      description: ''
      spec:
      - question_name: Project
        question_description: Project code
        choices: ''
        default: ''
        max: 10
        min: 2
        required: false
        type: text
        variable: project

          
- name: 'Deploy Linux VM in Azure'
  description: ''
  allow_simultaneous: true
  description: ''
  execution_environment: 'Azure Execution Environment'
  extra_vars:
    os_type: Linux
    ansible_python_interpreter: /usr/bin/python3
  inventory: 'Cloud'
  playbook: 'azure_create_vm.yml'
  project: 'Azure Playbooks'
  credentials: 'Azure'
  survey_enabled: true
  related:
    survey_spec:
      name: ''
      description: ''
      spec:
      - question_name: 'Project'
        question_description: 'Project name to which this VM belongs'
        choices: ''
        default: ''
        max: 10
        min: 2
        new_question: true
        required: false
        type: 'text'
        variable: 'project'
      - question_name: 'Name'
        question_description: 'VM name'
        choices: ''
        default: ''
        max: 30
        min: 4
        required: false
        type: 'text'
        variable: 'vm_name'
      - question_name: 'Role'
        question_description: 'The role of this VM'
        choices: 'webserver
        
        lbserver
        
        dbserver'
        default: ''
        max: null
        min: null
        new_question: true
        required: true
        type: 'multiplechoice'
        variable: 'role'


- name: 'Deploy Web site'
  description: ''
  extra_vars: 
    git_base: https://github.com/fvzwieten
  inventory: 'Cloud'
  playbook: 'update_website.yml'
  project: 'Web Farm Demo'
  credentials: 'Linux'
  webhook_credential: 'GitHub Website'
  webhook_service: 'github'
    
- name: 'Install DB Server'
  description: ''
  inventory: 'Cloud'
  playbook: 'deploy_dbservers.yml'
  project: 'Web Farm Demo'
  credentials: 'Linux'

    
- name: 'Install Linux Baseline'
  description: ''
  execution_environment: 'Execution Environment for RBAC Demo'
  inventory: 'Cloud'
  playbook: 'deploy_common.yml'
  project: 'Web Farm Demo'
  credentials: 'Linux'
    
- name: 'Install Load Balancer'
  description: ''
  inventory: 'Cloud'
  playbook: 'deploy_lbservers.yml'
  project: 'Web Farm Demo'
  credentials:
    - 'Linux'
    - 'Proxy Stats'
    
- name: 'Install Web Server'
  description: ''
  execution_environment: 'Execution Environment for RBAC Demo'
  inventory: 'Cloud'
  playbook: 'deploy_webservers.yml'
  project: 'Web Farm Demo'
  credentials: 'Linux'

- name: 'Rolling update Webfarm'
  description: 'Lifecycle the webfarm installation'
  execution_environment: 'Execution Environment for RBAC Demo'
  inventory: 'Cloud'
  playbook: 'rolling_update.yml'
  project: 'Web Farm Demo'
  credentials: 'Linux'
  related:
    survey_spec:
      name: ''
      description: ''
      spec:
      - question_name: 'Project'
        question_description: 'Project name for the web farm to lifecycle'
        choices: ''
        default: ''
        max: 10
        min: 2
        new_question: true
        required: true
        type: 'text'
        variable: 'project'
        
- name: 'Verify RHEL baseline'
  description: 'Make sure all RHEL machines have the same baseline'
  inventory: null
  playbook: ''
  project: null
