controller_user_accounts:
- username: admin
  email: admin@example.com
  first_name: Admin
  last_name: Guy
  is_superuser: true
- username: auditguy
  email: auditguy@example.com
  first_name: Audit
  last_name: Guy
  is_system_auditor: true
- username: cloudguy
  email: azure@example.com
  first_name: Cloud
  last_name: Guy
- username: contentguy
  email: content@example.com
  first_name: Content
  last_name: Guy
- username: databaseguy
  email: databaseguy@example.com
  first_name: Database
  last_name: Guy
- username: linuxguy
  email: linuxguy@example.com
  first_name: Linux
  last_name: Guy
- username: networkguy
  email: networkguy@example.com
  first_name: Network
  last_name: Guy
- username: storageguy
  email: storage.guy@example.com
  first_name: Storage
  last_name: Guy
- username: webguy
  email: web@example.com
  first_name: Web
  last_name: Guy
- username: windowsguy
  email: windowsguy@example.com
  first_name: Windows
  last_name: Guy
