---

# httpd is handled by the base-apache role upstream
- name: Install php and git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - php
   - php-mysqlnd
   - php-cli
   - git

- name: reload apache
  service:
    name: httpd
    state: restarted

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: Configure firewall for access
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes

- name: Create Facts Dir on Managed Hosts
  file:
    path: "{{ facts_dir }}"
    state: directory
    recurse: yes

- name: Write the webserver configuration version out as a custom fact
  ini_file:
    path: "{{ facts_dir }}/webserver.fact"
    section: general
    option: version
    value: 1
  when: mode == "deploy"

- name: Update webserver configuration version custom fact
  ini_file:
    path: "{{ facts_dir }}/webserver.fact"
    section: general
    option: version
    value: "{{ ansible_facts['ansible_local']['webserver']['general']['version'] | int }} + 1"
  when: mode == "update"

- name: show version
  debug:
    msg: "{{ ansible_facts['ansible_local']['webserver']['general']['version'] | int }} + 1"

- name: Write the webserver serial out as a custom fact
  ini_file:
    path: "{{ facts_dir }}/webserver.fact"
    section: general
    option: serial
    value: "{{ lookup('ansible.utils.index_of', ansible_play_hosts, 'eq', inventory_hostname) }}"
