---

# httpd is handled by the base-apache role upstream
- name: Install php and git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - php
   - php-mysql
   - git

- name: reload apache
  service:
    name: httpd
    state: restarted

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
  when: sestatus.rc != 0

- name: Configure firewall for access
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes
  tags: fw

- name: Write the website configuration
  ini_file:
    path: /etc/webserver.conf
    section: general
    option: version
    value: 1
    mode: 0600
    backup: no

- ini_file:
    path: /etc/webserver.conf
    section: general
    option: color
    value: red
    backup: no
