---
# This role contains common plays that will run on all nodes

- name: Refresh subscription data
  yum:
    name: "*"
    state: latest
    disablerepo: "*"
    enablerepo: "*microsoft*"
  
- name: Install python bindings for SE Linux
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - libselinux-python
   - libsemanage-python

- include_role:
    name: geerlingguy.ntp

- name: Start the firewalld service
  service:
    name: firewalld
    state: started
    enabled: true
  tags: fw

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
